// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WeightWatchers.Data.Models;

public partial class WeightWatchersContext : DbContext
{
    public WeightWatchersContext(DbContextOptions<WeightWatchersContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Person> Person { get; set; }

    public virtual DbSet<Weight> Weight { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>(entity =>
        {
            entity.HasKey(e => e.PersonId).HasName("PK__Person__AA2FFBE5AA5F4B0A");

            entity.HasIndex(e => new { e.FirstName, e.LastName }, "UC_Person").IsUnique();

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Weight>(entity =>
        {
            entity.HasKey(e => new { e.Date, e.PersonId }).HasName("PK__Weight__3D9A82B8EC397BF6");

            entity.Property(e => e.Kgs).HasColumnType("decimal(4, 1)");
            entity.Property(e => e.Lbs).HasColumnType("decimal(4, 1)");

            entity.HasOne(d => d.Person).WithMany(p => p.Weight)
                .HasForeignKey(d => d.PersonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PersonId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}